### PR TITLE
add okcomputer check for rabbitmq queue existence

### PR DESCRIPTION
**Pull request by peetucket**
# Why was this change made? 🤔

Because if these queues are not setup correctly, it can cause weird unexpected behavior.

Can be fixed with a `RAILS_ENV=production bin/rake rabbitmq:setup` on the server, but at least this alerts us to the problem.

# How was this change tested? 🤨

Deployed to stage.

Screen Shot 2023-12-11 at 3 56 44 PM

### CODE REVIEW

**Review by ndushay — APPROVED** [review]
Shouldn't the queue initialization be done in its own initializer, rather than here?   I would never think to look here for it.

**Review by ndushay — CHANGES_REQUESTED** [review]
see previous comment

**Review by justinlittman — APPROVED** [review]

**Comment by peetucket** [comment]
> Shouldn't the queue initialization be done in its own initializer, rather than here? I would never think to look here for it.

It's a good question, and there is an initializer for the workers: https://github.com/sul-dlss/pre-assembly/blob/main/config/initializers/sneakers.rb  

But after looking through the documentation, I couldn't find a way to hook into this connection, so just decided to open a new one in the okcomputer check to verify the queue existence.  Definitely open to suggestions if I am missing something.

**Comment by ndushay** [comment]
this is for an old version of rails, but I searched on `rails initializer order`  and got to https://guides.rubyonrails.org/v2.3/configuring.html#using-an-after-initializer 

And there's also the config boot file, which I *think* executes before initializers.

I think it's worth it to get the queue initialized in a rabbitmq_initializer and then do the okcomputer ones after the other regular initializers ... however that is implemented.

**Comment by ndushay** [comment]
more current:  https://guides.rubyonrails.org/configuring.html#initialization-events

**Comment by peetucket** [comment]
> more current: https://guides.rubyonrails.org/configuring.html#initialization-events

So I'm not quite sure how to connect to the rabbit instance setup in the initializer regardless of order.  Can you say more about how you were thinking this would work in the context of the ok computer check?

**Comment by justinlittman** [comment]
We re-initialize in OKComputer for other checks as well. See, for example: https://github.com/sul-dlss/happy-heron/blob/main/config/initializers/okcomputer.rb#L8-L15

**Comment by justinlittman** [comment]
@ndushay Can you please provide clarification or unblock?

**Review by ndushay — APPROVED** [review]

**Pull request merged**
