### PR TITLE
The user.sunet_id is saved w/ the email not the username

### PR DESCRIPTION
**Pull request by SaravShah**
RSpec tests use only the username, need to fix to use the email

### CODE REVIEW

**Comment by atz** [comment]
I'm confused on this one.  I thought the sunet_id was what was part of the model, not the email.  But this treats the field as containing the full address.

**Comment by SaravShah** [comment]
Ah the sunet_id is already in email form:
```
 #<User id: 1, sunet_id: "saravs@stanford.edu", created_at: "2018-09-17 19:55:49", updated_at: "2018-09-17 19:55:49">
```

/shrug

**Comment by SaravShah** [comment]
yeah @ndushay im not sure which way we should go, either
1. keep the field as sunet_id and just add a helper method to strip off everything after the "@" sign
2. change field to email and leave it as is.

**Comment by peetucket** [comment]
I added an `.email` convenience method on the user model in #302 that we can alter later when/if we split sunet_id from email.  I would suggest keeping them separate (i.e. doing a stripping if needed on stroage in the sunet_id column -- would make it future proof if auth handoff changes in the future.

**Comment by jmartin-sul** [comment]
@atz, yeah, what we get as "sunetid" from webauth/shib is actually the whole email address.  my guess is that's something to do w/ shib allowing multiple institutions, and so maybe the domain qualifier really is part of the name?  anyway, the tests do now better reflect reality, even if our field name now seems a little confusing.

**Pull request merged**
