### PR TITLE
[WIP] Update dependencies, standardize deploy stage names

### PR DESCRIPTION
**Pull request by jmartin-sul**
NOTE: this bumps active-fedora from 6.x to 8.x and it would be good to have integration tests to be sure this is acceptable

Also note that the configuration of dor_services URL changes from dor.service_root to dor_services.url, which requires changing the configuration files on the servers (and likely any local config files you have that are not checked in here) when this deployed

### CODE REVIEW

**Comment by peetucket** [comment]
did some local tests; can't get integration tests to run, but this may not be fully indicative of a problem (they aren't running on master either)

there are some config changes for dor services url to bring it up to standard; pushed a commit to do this

next step is probably deploy to -test and actually run it

**Comment by peetucket** [comment]
deployed to -test, updated configs and tested a single object, works ok: https://argo-stage.stanford.edu/view/druid:zm588cc3646


NOTE: if merged and deployed to -prod, you need to update the "~/pre-assembly/shared/config/environments/production.rb" file manually as shown below (basically block name goes from "dor" to "dor_services" and "service_root" goes to "url").  This file is just on the server (no shared_configs)

```
dor do
    service_root 'XXXXXXXX'
    num_attempts  5  # the number of attempts to contact the dor web service before throwing an exception
    sleep_time   120  # sleep time in seconds between attempts to contact the dor service
    default_label 'Untitled' # the default label for an object that is registered when no label is provided in the manifest
  end
```

to 

```
dor_services do
    url 'XXXXXXX'
    num_attempts  5  # the number of attempts to contact the dor web service before throwing an exception
    sleep_time   120  # sleep time in seconds between attempts to contact the dor service
    default_label 'Untitled' # the default label for an object that is registered when no label is provided in the manifest
  end
```

**Comment by jcoyne** [comment]
@jmartin-sul this needs a rebase.

**Comment by peetucket** [comment]
@jmartin-sul ... i've giving the rebase a shot and can force push a branch when done.

**Comment by peetucket** [comment]
well i resolved all of the conflicts, confirmed i wasn't losing any critical changes on this branch, and then force-pushed -- tests pass and there are no conflicts, but i don't understand why it thinks there are so many changes between this branch and master 

honestly, i'd recommend just closing this PR and not proceeding - the main thrust of this PR was to standardize deploy names and update dependencies and that work had been done in other PRs in the time this was opened

**Comment by jmartin-sul** [comment]
@peetucket said:
> honestly, i'd recommend just closing this PR and not proceeding - the main thrust of this PR was to standardize deploy names and update dependencies and that work had been done in other PRs in the time this was opened

no objections from me

**Pull request closed without merging**
