### PR TITLE
[HOLD] Transition job run to preassembly_complete_with_errors when all associated accessions failed

### LINKED ISSUE #1309: if all druids fail at preassembly and do not proceed to accessioning, do not change the state to "Accessioning complete"
There is a possibility that an entire batch of druids fails to make it through Preassembly and on to accessioning. The simplest case is when there is only one druid and that druid fails during Preassembly. But that could happen with an entire batch. When that happens, the state should not transition to "Accessioning completed (with Preassembly errors)". It should be reported as "Preassembly completed with errors" (or whichever is the precise name for that state).

Note that Preassembly kicks of accessioning serially by druid, so you won't know if all druids have failed to start accessioning until the last druid in the batch has been processed.

### PR DESCRIPTION
**Pull request by mjgiarlo**
# Why was this change made?

Fixes #1309

# How was this change tested?

- [x] CI
- [ ] QA/stage

# Does your change introduce accessibility violations?

No.

### CODE REVIEW

**Review by jmartin-sul — COMMENTED** [review]
So `JobRunCompleteJob.perform_later` gets called when an accession completes: https://github.com/sul-dlss/pre-assembly/blob/7441a9b8a3110b99d8b52b0bb6b1ab626b830335/app/jobs/accession_complete_job.rb#L50

and also by `PreassemblyJob` in a use i don't quite understand (given the RabbitMQ-driven use linked above): https://github.com/sul-dlss/pre-assembly/blob/7441a9b8a3110b99d8b52b0bb6b1ab626b830335/app/jobs/preassembly_job.rb#L18

So, this might be incorrect, but my assumption was that `JobRunCompleteJob` should only fire when an accession completes, and that it's attempting to see whether all launched accessioning has completed yet.  But the situation Andrew describes in his bug seems to me like one where no accessioning would have been launched in the first place.

I figured the issue was that something was sending the `accessioning_completed` event to the `JobRun` instance in some scenario where that message shouldn't have been sent at all, and instead should've left the job in `preassembly_complete_with_errors`.  And so I'm also surprised by the new `JobRun` transitions, since I'm imagining something where the state was already `preassembly_complete_with_errors`.

I wonder if the thing to do is something like a `return unless job_run.accessions.exists?` guard clause right above `return if job_run.accessions.exists?(state: :in_progress)`.  Because if there are no accessions, `JobRunCompleteJob` will fall through to `job_run.accessioning_completed` as things stand?  I think?  It wouldn't be running (first guard clause passed), it wouldn't yet be marked as accessioning complete (2nd guard clause passed), and there would exist no `in_progress` accessions because there'd be no accessions (third guard clause passed).  And I think that the `JobRunCompleteJob.perform_later` at the end of `JobRun` could trigger that situation, if the given `JobRun` finishes and gets out of the `running` state before the `JobRunCompleteJob` it launched gets executed?

Not requesting changes, because I'm not sure my understanding is correct. Would be good for @justinlittman or @edsu to weigh in.

**Review by justinlittman — CHANGES_REQUESTED** [review]
#1307 gets rid of the *_completed_with_errors states. Also, I think you're confusing preassembly (the work that prepares for accessioning) and accessioning. Happy to discuss.

**Comment by mjgiarlo** [comment]
@justinlittman 💬 
> I think the part that you are missing is that an Accession is only created when accessioning is initiated. Thus, it should be sufficient to just add an additional guard clause in `JobRunCompleteJob` like `return if job_run.accessions.empty?`

Appreciate that. Have another look?

**Review by jmartin-sul — APPROVED** [review]

**Comment by edsu** [comment]
> I scoured the README and the wiki before getting started, and I didn't find much detail on the basic domain model and operating assumptions around these bits, but I certainly could have missed it. (Maybe this is me re-learning the lesson of trying not to context switch from app to app during the work cycle, and I should stick with Argo issues while that's loaded in my brain.)

The docs definitely needs a refresh given the work that has been done in this work cycle. #1221

**Comment by edsu** [comment]
@andrewjbtw is this one you would like to test before it gets merged?

**Review by justinlittman — APPROVED** [review]

**Comment by edsu** [comment]
In the interests of getting the production dependency updates out we are going to declare victory on this one, and resolve to fix any remaining problems as they come up.

**Review by edsu — APPROVED** [review]

**Pull request merged**
