### PR TITLE
test data: add smpl_multimedia and config yaml for it

### PR DESCRIPTION
**Pull request by ndushay**
This is basically bundle_input_e with a better name and a project yaml file that is configured for it.

Connects to #218
Connects to #199

### CODE REVIEW

**Comment by atz** [comment]
This seems certain to conflict w/ Sarav's PR

**Comment by ndushay** [comment]
i can redo this after #256.   For the record, this was up to be merged well before Sarav started on #256.

**Comment by atz** [comment]
Only a couple minor conflicts, rn.

**Comment by ndushay** [comment]
this has been rebased and is ready for review

**Pull request merged**
