### PR TITLE
'media' content-type, not 'smpl'

### PR DESCRIPTION
**Pull request by ndushay**
~~do not merge until vetted by stakeholder!!!~~

Note:  this ~~needs to be~~ has been vetted by @andrewjbtw on preassembly stage ~~before it is~~ so it can be merged to master.  ~~Hence it is a draft until then.~~

Changes to address issue #515 (change refs to "smpl" content-type to "media").

Replaces draft PR #518 -- d5d6daa shows why travis build was failing -- our laptop mac os-x didn't care about the case of the initial "M" but travis did -- the directory name needs to match the project name.

In the course of looking for the solution, I found some other references to "smpl" which I changed, and I think a couple corrections from 60d562f.  If you're curious, review each commit in turn.

### CODE REVIEW

**Comment by ndushay** [comment]
@andrewjbtw this is deployed to sul-preassembly-stage;  can you please vet the changes and let us know if this addresses your concerns for issue #515 ?

**Comment by ndushay** [comment]
when merged, please be sure to delete this branch and `smpl-to-media-refs` as well, if it's not already gone.

**Comment by andrewjbtw** [comment]
This looks good. We tested on preassembly-stage with an example from a real accession and everything checked out.

**Comment by ndushay** [comment]
when merged, please be sure to delete this branch and smpl-to-media-refs as well, if it's not already gone.

**Pull request merged**
