### PR TITLE
[HOLD] Updated to Boostrap 5. Switched to using foreman, jsbundling, cssbund…

### LINKED ISSUE #926: Upgrade to bootstrap 5
Currently we're on bootstrap 4

### PR DESCRIPTION
**Pull request by justinlittman**
…ling.

closes #926

## Why was this change made? 🤔
Consistency with other apps.

## How was this change tested? 🤨

⚡ ⚠ If this change has cross service impact (e.g. changes what is written to shared file systems or how it uses APIs), ***run [integration tests](https://github.com/sul-dlss/infrastructure-integration-test)*** and/or test in [stage|qa] environment, in addition to specs. ⚡

Integration test

### CODE REVIEW

**Comment by andrewjbtw** [comment]
(I think this is the right PR to comment on - I'm testing Preassembly with `t926-bootstrap` deployed.)

There are a few issues in the Preassembly interface with BS5 deployed.

1. The recent jobs list on the front page is not being populated. (The "All jobs" page is being populated, so it's just the front page.)

Stage:
Screen Shot 2022-06-02 at 4 35 37 PM

Prod:
Screen Shot 2022-06-02 at 4 49 37 PM

2. Clicking the "details" button on the jobs pages doesn't expand to show the details

Discovery report example: https://sul-preassembly-stage.stanford.edu/job_runs/1671
Preassembly job example: https://sul-preassembly-stage.stanford.edu/job_runs/1670

A section with information about the job should appear after clicking the details button.

3. The layout of the "All projects" page and the display for individual projects shows the buttons vertically arranged. In the prod display the "New discovery report" and "Run preassembly" buttons are side by side.

Stage "All projects": https://sul-preassembly-stage.stanford.edu/batch_contexts
Prod "All projects": https://sul-preassembly-prod.stanford.edu/batch_contexts

Stage individual project: https://sul-preassembly-stage.stanford.edu/batch_contexts/1
Prod individual project: https://sul-preassembly-prod.stanford.edu/batch_contexts/1

4. No icons are showing in the project display for these two fields:

- staging style symlink
- using file manifest

Prod (fields are blank):
Screen Shot 2022-06-02 at 5 09 55 PM

Stage (see the checkmark and the X):

Screen Shot 2022-06-02 at 5 10 12 PM

Running the jobs seems to be fine. The only button or link that doesn't appear to be working is the "details" one.

**Review by jcoyne — CHANGES_REQUESTED** [review]
Is there a reason we need to bundle assets for this app? Can we do without sass?

**Comment by ndushay** [comment]
@justinlittman Bootstrap 5 PR - back to you.

**Comment by justinlittman** [comment]
@jcoyne I moved away from hardcoding the JS assets to this approach to be consistent with most other infra apps.

**Comment by ndushay** [comment]
I agree with JCoyne here ... that there are too many pieces this app doesn't need to warrant adding the whole magilla.

**Pull request closed without merging**
