### PR TITLE
Remove the thumb attribute, it's no longer used

### PR DESCRIPTION
**Pull request by jcoyne**
## Why was this change made? 🤔

We never end up using this attribute.

## How was this change tested? 🤨

⚡ ⚠ If this change has cross service impact (e.g. changes what is written to shared file systems or how it uses APIs), ***run [integration tests](https://github.com/sul-dlss/infrastructure-integration-test)*** and/or test in [stage|qa] environment, in addition to specs. ⚡

### CODE REVIEW

**Review by ndushay — COMMENTED** [review]
We also have specs that mention thumb and test files -- getting rid of those would also be indicated, no?

**Review by edsu — APPROVED** [review]
It looks like `thumb` is used in some spec data files, but I didn't see anything in the Ruby code either.

**Comment by jcoyne** [comment]
I think we want to continue to leave it in the input files/tests to show that we aren't breaking anything if people choose to provide it, we just don't need to do any processing on it.

**Comment by ndushay** [comment]
this is approved, but needs a rebase.

**Pull request merged**
